#!/bin/bash

scriptpath=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

dafny="$scriptpath/../../../local-dafny/Scripts/dafny"

dafnyVerify="$dafny /timeLimit:20 /compile:0  /noNLarith /autoTriggers:1 /vcsCores:8"

files="$scriptpath/../../lib/UtilitiesLibrary.dfy $scriptpath/../../lib/MonotonicityLibrary.dfy $scriptpath/../types.dfy $scriptpath/../hosts.dfy $scriptpath/distributedSystem.dfy $scriptpath/messageInvariants.dfy $scriptpath/applicationProof.dfy"

echo "Verifying $files" | tr " " "\n"

time $dafnyVerify $files