#!/bin/sh

scriptpath=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

dafny="$scriptpath/../../../local-dafny/Scripts/dafny"

dafnyMsgInv="$dafny /msgInvs"
dafnyAsyncProof="$dafny /genAsyncProof"
dafnyVerify="$dafny /timeLimit:20 /compile:0  /noNLarith /autoTriggers:1 /vcsCores:10"

rm -f messageInvariantsAutogen.dfy monotonicityInvariantsAutogen.dfy applicationProofDraftAutogen.dfy

# Generate Message Invariants and Monotonicity Invariants
$dafnyMsgInv "distributedSystem.dfy" > autoInvs.log

# Generate Async proof draft
$dafnyAsyncProof "../sync/applicationProof.dfy" > autoProof.log

# Verify files. In this case, the draft is not enough
files="$scriptpath/../../lib/* $scriptpath/../hosts.dfy $scriptpath/../types.dfy $scriptpath/distributedSystem.dfy $scriptpath/spec.dfy $scriptpath/monotonicityInvariantsAutogen.dfy $scriptpath/messageInvariantsAutogen.dfy $scriptpath/applicationProofDraftAutogen.dfy $scriptpath/applicationProof_demo.dfy"
echo "Verifying $files" | tr " " "\n"

time $dafnyVerify $files