#!/bin/sh

scriptpath=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

dafny="$scriptpath/../../../local-dafny/Scripts/dafny"

dafnyVerify="$dafny /timeLimit:20 /compile:0 /vcsCores:12 /noNLarith"

files="$scriptpath/../../lib/*.dfy $scriptpath/types.dfy $scriptpath/hosts.dfy $scriptpath/distributedSystem.dfy $scriptpath/spec.dfy $scriptpath/messageInvariants.dfy $scriptpath/applicationProof.dfy"

echo "Verifying $files" | tr " " "\n"

time $dafnyVerify $files